/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.AlunoDAO;
import DAO.CursoDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.Aluno;
import model.Curso;

/**
 *
 * @author usr
 */
public class CadAluno extends javax.swing.JFrame {

    /**
     * Creates new form Aluno
     */
    public CadAluno() throws SQLException {
        initComponents();
        setLocationRelativeTo( null );
        inicio();
    }
    
    private void clean(){
        jTxtmatricula.setText(null);
        jtxtNome.setText(null);
        jTXTCPF.setText(null);
        jTXTRG.setText(null);
        cbCurso.setSelectedIndex(-1);
    }
    
    public void Listar() throws SQLException{
    
        DefaultTableModel modelo = (DefaultTableModel) jTableAluno.getModel();
        AlunoDAO ad = new AlunoDAO();
        modelo.setRowCount(0);
        
        for (Aluno a : ad.read()) {
            
             modelo.addRow(new Object[]{
                a.getCodigo(),
                a.getMatricula(),
                a.getNome(),
                a.getRg(),
                a.getCpf(),
                a.getCurso()
             }
             );   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTxtmatricula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTXTRG = new javax.swing.JTextField();
        jTXTCPF = new javax.swing.JTextField();
        jtxtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBtInserir = new javax.swing.JButton();
        jBTAlterar = new javax.swing.JButton();
        jBTexcluir = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAluno = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbCurso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Matrícula:");

        jTxtmatricula.setName("txtMatricula"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("RG:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("CPF:");

        jTXTRG.setName("txtRG"); // NOI18N

        jTXTCPF.setName("txtCPF"); // NOI18N

        jtxtNome.setName("txtNome"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nome:");

        jBtInserir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtInserir.setText("Incluir");
        jBtInserir.setName("btIncluir"); // NOI18N
        jBtInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtInserirMouseClicked(evt);
            }
        });

        jBTAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTAlterar.setText("Alterar");
        jBTAlterar.setName("btAlterar"); // NOI18N
        jBTAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTAlterarMouseClicked(evt);
            }
        });

        jBTexcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTexcluir.setText("Excluir");
        jBTexcluir.setName("btAlterar"); // NOI18N
        jBTexcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTexcluirMouseClicked(evt);
            }
        });
        jBTexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTexcluirActionPerformed(evt);
            }
        });

        btFechar.setText("Fechar");
        btFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBTAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBTexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jBTexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jBTAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
            .addComponent(jBtInserir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jTableAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Matrícula", "Nome", "RG", "CPF", "Curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlunoMouseClicked(evt);
            }
        });
        jTableAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableAlunoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAluno);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Curso:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXTRG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 213, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jTXTRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTXTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTxtmatricula.getAccessibleContext().setAccessibleName("txtMatricula");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtInserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtInserirMouseClicked
        // TODO add your handling code here:
        Aluno a = new Aluno(jTxtmatricula.getText(),
                            jtxtNome.getText(),
                            jTXTCPF.getText(),
                            jTXTRG.getText(),
                            cbCurso.getSelectedItem().toString());
        
        AlunoDAO ad = new AlunoDAO();
        
        try {
            ad.insereAluno(a, a.getCurso());
            
            Listar();
        } catch (SQLException ex) {
            Logger.getLogger(CadAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        clean();
             
    }//GEN-LAST:event_jBtInserirMouseClicked

    private void jBTexcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTexcluirMouseClicked
        // TODO add your handling code here:
        
        if (jTableAluno.getSelectedRow() != -1){

            Aluno a = new Aluno(0);
            
            AlunoDAO ad = new AlunoDAO();
            
            a.setCodigo((int) jTableAluno.getValueAt(jTableAluno.getSelectedRow(), 0));

            try {
                ad.deletaAluno(a);
            } catch (SQLException ex) {
                Logger.getLogger(CadAluno.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                Listar();
                
            } catch (SQLException ex) {
                Logger.getLogger(CadAluno.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBTexcluirMouseClicked

    private void jTableAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlunoMouseClicked
        // TODO add your handling code here:    
        Refresh();
    }//GEN-LAST:event_jTableAlunoMouseClicked

    private void jBTexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTexcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTexcluirActionPerformed

    private void jTableAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableAlunoKeyReleased
        // TODO add your handling code here:
        
        Refresh();
    }//GEN-LAST:event_jTableAlunoKeyReleased

    private void jBTAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTAlterarMouseClicked
        // TODO add your handling code here:
        
        if (jTableAluno.getSelectedRow() != -1){

            Aluno a = new Aluno(0);
            
            AlunoDAO ad = new AlunoDAO();
            a.setMatricula(jTxtmatricula.getText());
            a.setNome(jtxtNome.getText());
            a.setRg(jTXTRG.getText());
            a.setCpf(jTXTCPF.getText());
            a.setCodigo((int) jTableAluno.getValueAt(jTableAluno.getSelectedRow(), 0));
            a.setCurso(cbCurso.getSelectedItem().toString());
            
            try {
                ad.atualizaAluno(a);
                Listar();
            } catch (SQLException ex) {
                Logger.getLogger(CadAluno.class.getName()).log(Level.SEVERE, null, ex);
            }
            clean();
        }
    }//GEN-LAST:event_jBTAlterarMouseClicked

    private void btFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFecharMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btFecharMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadAluno().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CadAluno.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JComboBox<String> cbCurso;
    private javax.swing.JButton jBTAlterar;
    private javax.swing.JButton jBTexcluir;
    private javax.swing.JButton jBtInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTXTCPF;
    private javax.swing.JTextField jTXTRG;
    private javax.swing.JTable jTableAluno;
    private javax.swing.JTextField jTxtmatricula;
    private javax.swing.JTextField jtxtNome;
    // End of variables declaration//GEN-END:variables

    private void inicio() throws SQLException {   
       Listar();
       CarregaCombo();
       cbCurso.setSelectedIndex(-1);
    }

    private void Refresh() {
        if (jTableAluno.getSelectedRow() != -1){
            
            jTxtmatricula.setText(jTableAluno.getValueAt(jTableAluno.getSelectedRow(), 1).toString());
            jtxtNome.setText(jTableAluno.getValueAt(jTableAluno.getSelectedRow(), 2).toString());
            jTXTRG.setText(jTableAluno.getValueAt(jTableAluno.getSelectedRow(), 3).toString());
            jTXTCPF.setText(jTableAluno.getValueAt(jTableAluno.getSelectedRow(), 4).toString());
            cbCurso.setSelectedItem(jTableAluno.getValueAt(jTableAluno.getSelectedRow(), 5).toString());
        }
    }
    
    private void CarregaCombo() throws SQLException{
        DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) cbCurso.getModel();
        CursoDAO cd = new CursoDAO();
        
        for (model.Curso c : cd.ListarCombo()){ 
            comboBoxModel.addElement(c.getCodigo() + " - " +  c.getDescricao());    
        }
    }

}


