/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.CursoDAO;
import DAO.DisciplinaDAO;
import DAO.ProfessorDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.Disciplina;

/**
 *
 * @author usr
 */
public class CadDisciplina extends javax.swing.JFrame {

    /**
     * Creates new form CadDisciplina
     */
    public CadDisciplina() throws SQLException {
        initComponents();
        setLocationRelativeTo( null );
        inicio();
    }
    
    private void clean(){
        jTXTDescricao.setText(null);
        jTXTEmenta.setText(null);
        jTXTLimVagas.setText(null);
        jTXTCargaHoraria.setText(null);
        cbProfessor.setSelectedIndex(-1);
        cbDiaSemana.setSelectedIndex(-1);
    }
    
    public void refreshComboProf() throws SQLException{
        
        DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) cbProfessor.getModel();
        ProfessorDAO pd = new ProfessorDAO();
        
        for (model.Professor p : pd.readMestre()){ 
            comboBoxModel.addElement(p.getCodigo() + " - " +  p.getNome());    
        }
    }
    
    public void refreshComboCur() throws SQLException{
        
        DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) cbCurso.getModel();
        CursoDAO cd = new CursoDAO();
        
        for (model.Curso c : cd.Listar()){ 
            comboBoxModel.addElement(c.getCodigo() + " - " +  c.getDescricao());    
        }
    }
    
    private void inicio() throws SQLException{
        refreshComboProf();
        refreshComboCur();
        Listar();
    }
    
    public void Listar() throws SQLException{
    
        DefaultTableModel modelo = (DefaultTableModel) jTableDisciplina.getModel();
        DisciplinaDAO dd = new DisciplinaDAO();
        
        modelo.setRowCount(0);
        
        for (Disciplina d : dd.Listar()) {
            
             modelo.addRow(new Object[]{
                d.getCodigo(),
                d.getDescricao(),
                d.getEmenta(),
                d.getLimiteVaga(),
                d.getDiaSemana()
             }
             );   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDisciplina = new javax.swing.JTable();
        jBtIncluir = new javax.swing.JButton();
        jBtalterar = new javax.swing.JButton();
        jBtexcluir = new javax.swing.JButton();
        jBtFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTXTDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTXTEmenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbDiaSemana = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTXTLimVagas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbCurso = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbProfessor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTXTCargaHoraria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTableDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Ementa", "Limite Vagas", "Dia Semana", "Curso"
            }
        ));
        jTableDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDisciplinaMouseClicked(evt);
            }
        });
        jTableDisciplina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableDisciplinaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDisciplina);

        jBtIncluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtIncluir.setText("Incluir");
        jBtIncluir.setName("btIncluir"); // NOI18N
        jBtIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtIncluirMouseClicked(evt);
            }
        });

        jBtalterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtalterar.setText("Alterar");
        jBtalterar.setName("btAlterar"); // NOI18N
        jBtalterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtalterarMouseClicked(evt);
            }
        });

        jBtexcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtexcluir.setText("Excluir");
        jBtexcluir.setName("btAlterar"); // NOI18N
        jBtexcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtexcluirMouseClicked(evt);
            }
        });

        jBtFechar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtFechar.setText("Fechar");
        jBtFechar.setName("btAlterar"); // NOI18N
        jBtFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtFecharMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Descrição:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Ementa:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Dia da Semana:");

        cbDiaSemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domingo", "Segunda Feira", "Terça Feira", "Quarta Feira", "Quinta Feira", "Sexta Feira", "Sábado" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Limite de Vagas:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Curso:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Professor:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Carga Horária:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTXTEmenta)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTXTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXTLimVagas, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXTCargaHoraria)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTXTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTXTLimVagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTXTEmenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTXTCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jBtexcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jBtalterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jBtIncluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtIncluirMouseClicked
        // TODO add your handling code here:
        
        Disciplina d = new Disciplina(jTXTDescricao.getText(),
                                      jTXTEmenta.getText(),
                                      Integer.parseInt(jTXTLimVagas.getText()),
                                      cbProfessor.getSelectedIndex()+1,
                                      cbDiaSemana.getSelectedItem().toString(),
                                      Integer.parseInt(jTXTCargaHoraria.getText()));
        
        DisciplinaDAO dd = new DisciplinaDAO();
        try {
            dd.insereDisciplina(d);
            
            Listar();
        } catch (SQLException ex) {
            Logger.getLogger(CadDisciplina.class.getName()).log(Level.SEVERE, null, ex);
        }
        clean();
        
    }//GEN-LAST:event_jBtIncluirMouseClicked
    
    private void refresh(){
    if (jTableDisciplina.getSelectedRow() != -1){
            
            jTXTDescricao.setText(jTableDisciplina.getValueAt(jTableDisciplina.getSelectedRow(), 1).toString());
            jTXTEmenta.setText(jTableDisciplina.getValueAt(jTableDisciplina.getSelectedRow(), 2).toString());
            jTXTLimVagas.setText(jTableDisciplina.getValueAt(jTableDisciplina.getSelectedRow(), 3).toString());
            cbDiaSemana.setSelectedItem(jTableDisciplina.getValueAt(jTableDisciplina.getSelectedRow(), 4).toString());
        }
    }
    
    private void jBtFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtFecharMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtFecharMouseClicked

    private void jTableDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDisciplinaMouseClicked
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jTableDisciplinaMouseClicked

    private void jTableDisciplinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableDisciplinaKeyReleased
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jTableDisciplinaKeyReleased

    private void jBtalterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtalterarMouseClicked
        // TODO add your handling code here:
        if (jTableDisciplina.getSelectedRow() != -1){

            Disciplina d = new Disciplina(0);
            
            DisciplinaDAO dd = new DisciplinaDAO();
            
            d.setDescricao(jTXTDescricao.getText());
            d.setEmenta(jTXTEmenta.getText());
            d.setLimiteVaga(Integer.parseInt(jTXTLimVagas.getText()));
            d.setProfessor(cbProfessor.getSelectedIndex()+1);
            d.setCodigo((int) jTableDisciplina.getValueAt(jTableDisciplina.getSelectedRow(), 0));
            d.setDiaSemana(cbDiaSemana.getSelectedItem().toString());
            
            try {
                dd.atualizadisciplina(d);
                Listar();
            } catch (SQLException ex) {
                Logger.getLogger(CadDisciplina.class.getName()).log(Level.SEVERE, null, ex);
            }
            clean();
        }
    }//GEN-LAST:event_jBtalterarMouseClicked

    private void jBtexcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtexcluirMouseClicked
        // TODO add your handling code here:
        
         if (jTableDisciplina.getSelectedRow() != -1){

            Disciplina d = new Disciplina(0);
            
            DisciplinaDAO dd = new DisciplinaDAO();
            
            d.setCodigo((int) jTableDisciplina.getValueAt(jTableDisciplina.getSelectedRow(), 0));

            try {
                dd.deletadisciplina(d);
            } catch (SQLException ex) {
                Logger.getLogger(CadDisciplina.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                Listar();
                
            } catch (SQLException ex) {
                Logger.getLogger(CadAluno.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBtexcluirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadDisciplina().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CadDisciplina.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCurso;
    private javax.swing.JComboBox<String> cbDiaSemana;
    private javax.swing.JComboBox<String> cbProfessor;
    private javax.swing.JButton jBtFechar;
    private javax.swing.JButton jBtIncluir;
    private javax.swing.JButton jBtalterar;
    private javax.swing.JButton jBtexcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTXTCargaHoraria;
    private javax.swing.JTextField jTXTDescricao;
    private javax.swing.JTextField jTXTEmenta;
    private javax.swing.JTextField jTXTLimVagas;
    private javax.swing.JTable jTableDisciplina;
    // End of variables declaration//GEN-END:variables
}
